# Generated by Django 3.2.18 on 2023-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='food_relation',
            field=models.CharField(choices=[('CHEF', 'Chef'), ('NUTRITIONIST', 'Nutritionist'), ('PASTRY_CHEF', 'Pastry Chef'), ('FOOD_STYLIST', 'Food Stylist'), ('CULINARY_INSTRUCTOR', 'Culinary Instructor'), ('FOOD_CRITIC', 'Food Critic'), ('HOME_COOK', 'Home Cook'), ('OTHER', 'Other')], default='HOME_COOK', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/users/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
