# Generated by Django 3.2.18 on 2023-04-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230421_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='food_relation',
            field=models.CharField(max_length=200),
        ),
    ]
