# Generated by Django 3.2.18 on 2023-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_food_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Citizen of the world', max_length=200),
        ),
    ]
