# Generated by Django 3.2.18 on 2023-05-10 10:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/sandrabergstrom/image/upload/v1683715797/User_f3gwvv.jpg', max_length=255, verbose_name='image'),
        ),
    ]
