# Generated by Django 3.2.18 on 2023-05-17 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/sandrabergstrom/image/upload/v1684322604/user_zyrx8b.png', max_length=255, verbose_name='image'),
        ),
    ]
