# Generated by Django 3.2.18 on 2023-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('APPETIZERS', 'Appetizers'), ('BREAKFAST', 'Breakfast'), ('MAIN_DISHES', 'Main Dishes'), ('DESSERTS', 'Desserts'), ('SALLADS', 'Sallads'), ('SIDE_DISHES', 'Side Dishes'), ('SNACKS', 'Snacks'), ('OTHER', 'Other')], default='MAIN_DISHES', max_length=30),
        ),
    ]
