# Generated by Django 3.2.18 on 2023-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0),
        ),
    ]
