# Generated by Django 3.2.18 on 2023-04-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_recipe_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
    ]
