# Generated by Django 3.2.18 on 2023-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20230421_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='excerp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
