# Generated by Django 3.2.18 on 2023-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20230421_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='about',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
