# Generated by Django 3.2.18 on 2023-05-17 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_auto_20230516_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/sandrabergstrom/image/upload/v1684323615/placeholder_ywziah.jpg', max_length=255, verbose_name='image'),
        ),
    ]
